ARCHS = armv7 armv7s arm64
include theos/makefiles/common.mk

internal-stage::
	$(ECHO_NOTHING)mkdir -p $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences$(ECHO_END)
	$(ECHO_NOTHING)cp TapTapFlip.plist $(THEOS_STAGING_DIR)/Library/PreferenceLoader/Preferences/TapTapFlip.plist$(ECHO_END)